name: Flutter drive

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  drive:
    strategy:
      matrix:
        device:
          - "iPhone 12 mini"
      fail-fast: false
    runs-on: macos-11
    steps:
      - uses: futureware-tech/simulator-action@v1
        with:
          model: ${{ matrix.device }}
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: "cd example && flutter drive --target=test_driver/app.dart"