name: Flutter drive Linux

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: sudo apt-get update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
      - name: install deps
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
      - run: "cd example && flutter drive -d linux --profile --target=test_driver/app.dart"