name: Flutter drive Windows

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  e2e:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: install deps
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
      - run: "cd example && flutter drive -d windows --target=test_driver/app.dart"