name: Flutter drive

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  drive:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: "cd example && flutter drive --target=test_driver/app.dart"