name: Hover

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - uses: actions/setup-go@v2
      - run: GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover@latest
      - name: config
        run: |
          git config user.name "${{ env.GITHUB_REPOSITORY_OWNER }}"
          git config user.email "bot@github.com"
          git remote remove origin || echo "skipped"
          git remote add origin "https://${{ env.GITHUB_REPOSITORY_OWNER }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
      - run: yes | `go env GOPATH`/bin/hover publish-plugin