name: Integration Tests macOS

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  e2e:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'dev'
      - name: install deps
        run: |
          flutter config --enable-macos-desktop
          flutter pub get
          cd example/macos && pod install
      - run: "cd example && flutter test -d macos integration_test/app_test.dart"