name: Integration Tests iOS

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  e2e:
    runs-on: macos-11
    steps:
      - uses: futureware-tech/simulator-action@v1
        with:
          model: "iPhone 12 mini"
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: install deps
        run: |
          flutter pub get
          cd example/ios && pod install
      - run: "cd example && flutter test integration_test/app_test.dart"